### ISSUE TITLE
[security] please declare license

### ISSUE THREAD

**Issue by fuchanghai** [tevaera-labs/core-contracts#3]
You'd better declare your license, otherwise you may have code attribution issues and other bad issues

**Comment by fuchanghai** [comment]
@gauravladani  @gauravl-tevaeralabs  PTAL

**Comment by gauravl-tevaeralabs** [comment]
This repository mainly contains contracts, and each contract is under the BUSL license. The following line can be found in every Solidity file:

// SPDX-License-Identifier: BUSL-1.1

**Comment by fuchanghai** [comment]
<img width="1439" alt="image" src="https://github.com/tevaera-labs/contracts/assets/33984497/407bb2b3-40bc-4636-85b5-9426f9a4e630">
hi @gauravl-tevaeralabs I think the license needs to be stated here as well

**Comment by gauravl-tevaeralabs** [comment]
I've added it to this repo. Thanks!
